### ISSUE TITLE
hard coding

### ISSUE THREAD

**Issue by SaidBySolo** [ArceRoot/Ri_A_Co#8]
https://github.com/ArceRoot/Ri_A_Co/blob/0ac75b75d9420a4abd9ab206ec3ffded028b903a/modules/eventhandle.py#L43
https://github.com/ArceRoot/Ri_A_Co/blob/0ac75b75d9420a4abd9ab206ec3ffded028b903a/modules/eventhandle.py#L45
can using ``string.ascii_letters``

**Comment by ArceRoot** [comment]
더 이상 해당 코드를 쓸 곳이 없기에 기각합니다.

**Comment by SaidBySolo** [comment]
풀리퀘 넣으면 머지 하나요

**Comment by ArceRoot** [comment]
예 넣으시면 머지해드릴게요
